# 端口号
server:
  port: 8001

# 系统配置
spring:
  aop:
    auto: true
    proxy-target-class: true
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/zhaodaola?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: Pangyi@1125
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 25
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    timeout: 5000
    password:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 60MB

# Mybatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.sise.zhaodaola.business.entity
  global-config:
    banner: false
  type-enums-package: com.sise.zhaodaola.business.enums

# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples: debug

# 文件存储路径
file:
  path: /Users/pangyi/Documents/WorkProjects/zhaodaola-admin/assets/file /
  avatar: /Users/pangyi/Documents/WorkProjects/zhaodaola-admin/assets/avatar/
  # 文件大小 /M
  maxSize: 100
  avatarMaxSize: 5

#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 14400000
  # 在线用户key
  online-key: online-token
  # 验证码
  code-key: code-key

#登录图形验证码有效时间/分钟
loginCode:
  expiration: 2
