# 端口号
server:
  port: 8001

# 系统配置
spring:
  aop:
    auto: true
    proxy-target-class: true
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://127.0.0.1:3306/zhaodaola?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: Pangyi@1125
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 25
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    timeout: 5000
    password:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 60MB

# Mybatis-Plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  type-aliases-package: com.sise.zhaodaola.business.entity

# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples: debug
